#!/bin/sh                                  

### BEGIN INIT INFO
# Provides:          app.pl
# Required-Start:    $all       
# Required-Stop:     $all       
# Default-Start:     2 3 4 5    
# Default-Stop:      0 1 6      
# Short-Description: vBulletin NNTP Gate
# Description:       Linux startup script for vBulletin NNTP Gate
### END INIT INFO                                              

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

OPTS=""
NAME="NNTP"
HOME="/var/www/forum.rcdesign.ru/nntp"
BIN="app.pl"
EXE="$HOME/$BIN"
PID="$HOME/var/appserver.pid"

test -x $EXE || exit 0                                       

ULIMIT=10240

RETVAL=0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --quiet --pidfile $PID \
      --exec $EXE -- start $OPTS || true
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "                        
    start-stop-daemon --stop --quiet --pidfile $PID \
      --signal "INT" || true
    echo "$NAME."                                                      
    ;;
  restart)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --pidfile $PID \
      --signal "INT" || true
    sleep 1
    start-stop-daemon --start --quiet --pidfile $PID \
      --exec $EXE -- start $OPTS || true
    echo "$NAME."
    ;;
  status)
    status_of_proc -p $PID "$PROG" $EXE && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    RETVAL=1
    ;;
esac

exit $RETVAL
